Fix ->desc
```java
//Here Plugin called kick on PreJoin or Join
[16:20:25] [Server thread/INFO]: robske_110[/188.105.108.13:19132] logged out due to You are banned: 
W 1: Reason: test1
W 2: Reason: lol
W 3: Reason: lol
W 4: Reason: more_test
W 5: Reason: lol
W 6: Reason: lol
W 7: Reason: lol
W 8: Reason: lol
W 9: Reason: lol
Fatal error: Call to a member function setHeldItemSlot() on null in phar:///Users/Tim/Desktop/Pocket_Server_0.13.x_TEST/PocketMine-MP.phar/src/pocketmine/Player.php on line 2067
[16:20:25] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[16:20:25] [Server thread/EMERGENCY]: Please upload the "/Users/Tim/Desktop/Pocket_Server_0.13.x_TEST/crashdumps/CrashDump_Sat_May_7-16.20.25-CEST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```